apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: IBM-Integration-Bus-V9
  description: Sin descripción
  annotations:
    github.com/project-slug: crlsquilumba/IBM-Integration-Bus-V9
    github.com/branch-count: "1"
    github.com/has-gitflow: "false"
    github.com/default-branch: "main"
  links:
    - url: https://github.com/crlsquilumba/IBM-Integration-Bus-V9/tree/main
      title: "✅ main — producción"
      icon: github
spec:
  type: library
  lifecycle: experimental
  owner: user:default/guest
